# Generated by Django 3.2.4 on 2021-11-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreusuario', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
    ]
